In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [10]:
df_match = pd.read_csv('../data/match_data_from2009-to2015.csv',index_col=0)
df_match = df_match[df_match['HomePoint'] != '中止']
for clm in ['HomePoint','AwayPoint']:
    df_match[clm] = pd.to_numeric(df_match[clm])
df_match.head()

           HomeTeam  HomePoint AwayTeam  AwayPoint Studium StartTime
Date
2009-04-03        中          4        横          1  ナゴヤドーム     18:00
2009-04-03        巨          3        広          6   東京ドーム     18:00
2009-04-03        阪          5        ヤ          2  京セラD大阪     18:00
2009-04-03        日          1        楽          3   札幌ドーム     18:00
2009-04-03        ソ          8        オ          0  ヤフードーム     18:00

In [11]:
df_match['HomePoint'].unique()

array([ 4,  3,  5,  1,  8,  2,  6, 10, 11,  9,  0, 13,  7, 15, 12, 16, 23,
       14, 19, 20, 22, 17, 18], dtype=int64)

In [12]:
gp = df_match.groupby('Studium')

In [28]:
sd_count = gp.count()['HomeTeam']
sd_count = count.sort_values(by='HomeTeam')[::-1]

In [29]:
sd_count

         HomeTeam  HomePoint  AwayTeam  AwayPoint  StartTime
Studium
東京ドーム         508        508       508        508        508
ナゴヤドーム        477        477       477        477        477
マツダスタ         476        476       476        476        476
神宮            463        463       463        463        463
横浜            459        459       459        459        459
京セラD大阪        458        458       458        458        458
甲子園           429        429       429        429        429
札幌ドーム         412        412       412        412        412
西武ドーム         410        410       410        410        410
QVCマリン        359        359       359        359        359
ヤフードーム        275        275       275        275        275
Ｋスタ宮城         202        202       202        202        202
ヤフオクドーム       201        201       201        201        201
千葉マリン         144        144       144        144        144
Kスタ宮城         134        134       134        134        134
コボスタ宮城        133        133       133        133        133
ほっと神戸          73         73        73         73         73
西武プリンス         69         69        69         69         69
スカイマーク         44         44        44         44         44
新潟             23         23        23         23         23
大宮             19         19        19         19         19
秋田             18         18        18         18         18
旭川             18         18        18         18         18
松山             17         17        17         17         17
北九州            13         13        13         13         13
帯広             12         12        12         12         12
那覇             11         11        11         11         11
郡山             11         11        11         11         11
静岡             10         10        10         10         10
函館             10         10        10         10         10
...           ...        ...       ...        ...        ...
浜松              7          7         7          7          7
熊本              7          7         7          7          7
京セラＤ大阪          7          7         7          7          7
金沢              6          6         6          6          6
鹿児島             6          6         6          6          6
前橋              6          6         6          6          6
平塚              5          5         5          5          5
宇都宮             5          5         5          5          5
福島              5          5         5          5          5
呉               5          5         5          5          5
三次              4          4         4          4          4
山形              4          4         4          4          4
尾道              4          4         4          4          4
米子              4          4         4          4          4
甲府              4          4         4          4          4
いわき             3          3         3          3          3
長崎              3          3         3          3          3
相模原             3          3         3          3          3
福井              3          3         3          3          3
ひたちなか           2          2         2          2          2
京都              2          2         2          2          2
東京ド             2          2         2          2          2
松本              2          2         2          2          2
皇子山             2          2         2          2          2
宮崎              1          1         1          1          1
佐賀              1          1         1          1          1
宇部              1          1         1          1          1
福山              1          1         1          1          1
札幌円山            1          1         1          1          1
広島              1          1         1          1          1

[66 rows x 5 columns]

In [30]:
min_games = 200
sd_count.StartTime
top10_st = sd_count.index[:10]

In [70]:
gp_points = df_match.groupby(['AwayPoint','HomePoint'],as_index=False).	HomeTeam.count().rename(columns = {'HomeTeam':'count'})

In [71]:
max_point = max(gp_points[['HomePoint','AwayPoint']].max())
print(max_point)

23

In [72]:
gp_points

     AwayPoint  HomePoint  count
0            0          0     16
1            0          1    155
2            0          2     96
3            0          3     90
4            0          4     69
5            0          5     52
6            0          6     42
7            0          7     32
8            0          8     18
9            0          9     14
10           0         10     11
11           0         11      3
12           0         12      3
13           0         13      1
14           0         15      2
15           1          0     68
16           1          1     38
17           1          2    241
18           1          3    146
19           1          4    130
20           1          5     76
21           1          6     57
22           1          7     52
23           1          8     33
24           1          9     29
25           1         10     18
26           1         11     13
27           1         12      4
28           1         13      4
29           1         14      1
..         ...        ...    ...
204         14          2      2
205         14          3      2
206         14          4      3
207         14          5      2
208         14          6      1
209         14          7      1
210         14         10      2
211         15          1      4
212         15          2      1
213         15          3      1
214         15          5      1
215         15          8      2
216         15          9      1
217         16          1      1
218         16          2      1
219         16          4      1
220         16          5      4
221         16          6      1
222         16         12      1
223         17          2      1
224         17          3      1
225         17          4      1
226         17          5      1
227         17         10      1
228         18          0      1
229         18          3      1
230         19          1      1
231         19          6      1
232         20         11      1
233         21         10      1

[234 rows x 3 columns]

In [61]:
point_hist = [[0] *24]*24

In [68]:
for i in range(0,max_point):
    for j in range(0,max_point):
        a =gp_points[(gp_points['AwayPoint'] == i ) & (gp_points['HomePoint'] == j )]['count']

In [69]:
a

Series([], Name: count, dtype: int64)

In [44]:
df_match.groupby(['Studium','HomePoint'],as_index=False).AwayPoint.count()

    Studium  HomePoint  AwayPoint
0     Kスタ宮城          0          7
1     Kスタ宮城          1         23
2     Kスタ宮城          2         20
3     Kスタ宮城          3         24
4     Kスタ宮城          4         16
5     Kスタ宮城          5         12
6     Kスタ宮城          6          8
7     Kスタ宮城          7          9
8     Kスタ宮城          8          6
9     Kスタ宮城          9          2
10    Kスタ宮城         10          4
11    Kスタ宮城         11          1
12    Kスタ宮城         14          1
13    Kスタ宮城         17          1
14   QVCマリン          0         31
15   QVCマリン          1         44
16   QVCマリン          2         54
17   QVCマリン          3         70
18   QVCマリン          4         40
19   QVCマリン          5         33
20   QVCマリン          6         24
21   QVCマリン          7         13
22   QVCマリン          8         19
23   QVCマリン          9         17
24   QVCマリン         10          5
25   QVCマリン         11          2
26   QVCマリン         12          4
27   QVCマリン         13          1
28   QVCマリン         14          1
29   QVCマリン         18          1
..      ...        ...        ...
454      長野          3          1
455      長野          6          2
456      長野          8          1
457      長野          9          1
458      静岡          0          2
459      静岡          2          2
460      静岡          4          2
461      静岡          5          1
462      静岡          6          1
463      静岡          7          1
464      静岡          8          1
465     鹿児島          4          2
466     鹿児島          5          1
467     鹿児島         10          1
468     鹿児島         11          1
469     鹿児島         15          1
470   Ｋスタ宮城          0         17
471   Ｋスタ宮城          1         24
472   Ｋスタ宮城          2         34
473   Ｋスタ宮城          3         32
474   Ｋスタ宮城          4         31
475   Ｋスタ宮城          5         22
476   Ｋスタ宮城          6         14
477   Ｋスタ宮城          7          5
478   Ｋスタ宮城          8          9
479   Ｋスタ宮城          9          7
480   Ｋスタ宮城         10          3
481   Ｋスタ宮城         11          1
482   Ｋスタ宮城         12          2
483   Ｋスタ宮城         14          1

[484 rows x 3 columns]